export type Post = {
  title: string
  url: string
  date: string
  description: string
  tags: string[]
  readingTime: string
  featured?: boolean
}

export const POSTS: Post[] = [
  {
    title: 'Shopify Left React Native for Native — And It Makes Sense',
    url: 'shopify_back_to_native',
    date: '2026-09-16',
    description: 'Shopify is moving from React Native back to Swift and Kotlin. AI agents made building twice cheap enough to choose native again.',
    tags: ['tech', 'mobile', 'react native', 'ai', 'generated by AI'],
    readingTime: '6 min',
  },
  {
    title: 'How to Stand Out as a Software Engineer in the AI Era',
    url: 'standout_ai_era',
    date: '2026-09-08',
    description: 'AI is changing everything — here\'s how to stay relevant, specialize deeply, and become irreplaceable as a software engineer.',
    tags: ['career', 'ai', 'software', 'generated by AI'],
    readingTime: '8 min',
    featured: true,
  },
  {
    title: 'Is Frontend Development Dead?',
    url: 'frontend_dev_dead',
    date: '2026-09-08',
    description: 'AI can generate UIs, no-code tools are powerful — so is frontend development actually dead? Spoiler: it\'s evolving.',
    tags: ['tech', 'frontend', 'future', 'generated by AI'],
    readingTime: '7 min',
  },
  {
    title: 'The Future of Coding: How AI Agents Are Changing Development',
    url: 'future_coding_ai',
    date: '2026-09-08',
    description: 'From code completion to autonomous agents — how AI is reshaping the way we write, debug, and ship software.',
    tags: ['tech', 'ai', 'future', 'generated by AI'],
    readingTime: '10 min',
  },
  {
    title: 'Building Interactive Portfolio Features with React',
    url: 'interactive_features',
    date: '2026-09-08',
    description: 'Adding custom cursor, scroll animations, dark mode, and more to create an engaging portfolio experience.',
    tags: ['tech', 'react', 'portfolio', 'generated by AI'],
    readingTime: '8 min',
  },
  {
    title: 'Revamping My Personal Website',
    url: 'revamp',
    date: '2025-06-15',
    description: 'How I redesigned my portfolio using React, TypeScript, and Tailwind CSS with modern interactive features.',
    tags: ['tech', 'portfolio', 'react', 'generated by AI'],
    readingTime: '5 min',
  },
  {
    title: 'My Stack for New Projects',
    url: 'my_stack',
    date: '2026-09-11',
    description: 'The stack I reach for when starting something new — React/Next.js for web, React Native or Flutter for mobile, Express or Go for the backend.',
    tags: ['tech', 'stack', 'react', 'go', 'flutter', 'generated by AI'],
    readingTime: '6 min',
  },
  {
    title: 'Tech Before AI — and What I\'d Do If I Switched to the Farm',
    url: 'pre_ai_farm',
    date: '2026-09-11',
    description: 'How development worked before AI — manual debugging, Stack Overflow, reading docs — and a half-serious plan for trading the terminal for a tractor.',
    tags: ['career', 'tech', 'personal', 'generated by AI'],
    readingTime: '5 min',
  },
  {
    title: 'Why I Created a Second GitHub Account — And Why I Moved Everything Back',
    url: 'git_account_consolidation',
    date: '2026-09-12',
    description: 'I split work vs personal across two GitHub accounts. It killed my visibility. Here is why I consolidated back to one and how to transfer repos safely.',
    tags: ['career', 'github', 'personal', 'generated by AI'],
    readingTime: '6 min',
  },
  {
    title: 'Hello World!',
    url: 'hello_world',
    date: '2025-06-12',
    description: 'My first post using MDX. Exploring the power of MDX for blog posts.',
    tags: ['tech', 'tutorial'],
    readingTime: '1 min',
  },
  {
    title: 'Summary',
    url: 'summary',
    date: '2025-06-10',
    description: 'A quick summary of what to expect from this blog.',
    tags: ['personal'],
    readingTime: '1 min',
  },
]

export function getPostsByTag(tag: string): Post[] {
  const posts = tag === 'all' ? POSTS : POSTS.filter(post => post.tags.includes(tag))
  return [...posts].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime())
}

export function getFeaturedPost(): Post | undefined {
  return POSTS.find(post => post.featured)
}

export function getAllTags(): string[] {
  const tags = new Set<string>()
  POSTS.forEach(post => post.tags.forEach(tag => tags.add(tag)))
  return Array.from(tags)
}

export function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

// Lazy load post components
export function getPostComponent(url: string) {
  switch (url) {
    case 'hello_world':
      return () => import('./hello_word.mdx')
    case 'summary':
      return () => import('./summary.mdx')
    case 'revamp':
      return () => import('./revamp.mdx')
    case 'interactive_features':
      return () => import('./interactive_features.mdx')
    case 'future_coding_ai':
      return () => import('./future_coding_ai.mdx')
    case 'frontend_dev_dead':
      return () => import('./frontend_dev_dead.mdx')
    case 'standout_ai_era':
      return () => import('./standout_ai_era.mdx')
    case 'my_stack':
      return () => import('./my_stack.mdx')
    case 'pre_ai_farm':
      return () => import('./pre_ai_farm.mdx')
    case 'git_account_consolidation':
      return () => import('./git_account_consolidation.mdx')
    case 'shopify_back_to_native':
      return () => import('./shopify_back_to_native.mdx')
    default:
      return null
  }
}
