export type Post = {
  title: string
  url: string
  date: string
  description: string
  tags: string[]
  readingTime: string
  featured?: boolean
}

export const POSTS: Post[] = [
  {
    title: 'How to Stand Out as a Software Engineer in the AI Era',
    url: 'standout_ai_era',
    date: '2026-09-08',
    description: 'AI is changing everything — here\'s how to stay relevant, specialize deeply, and become irreplaceable as a software engineer.',
    tags: ['career', 'ai', 'software', 'generated by AI'],
    readingTime: '8 min',
    featured: true,
  },
  {
    title: 'Is Frontend Development Dead?',
    url: 'frontend_dev_dead',
    date: '2026-09-08',
    description: 'AI can generate UIs, no-code tools are powerful — so is frontend development actually dead? Spoiler: it\'s evolving.',
    tags: ['tech', 'frontend', 'future', 'generated by AI'],
    readingTime: '7 min',
  },
  {
    title: 'The Future of Coding: How AI Agents Are Changing Development',
    url: 'future_coding_ai',
    date: '2026-09-08',
    description: 'From code completion to autonomous agents — how AI is reshaping the way we write, debug, and ship software.',
    tags: ['tech', 'ai', 'future', 'generated by AI'],
    readingTime: '10 min',
  },
  {
    title: 'Building Interactive Portfolio Features with React',
    url: 'interactive_features',
    date: '2026-09-08',
    description: 'Adding custom cursor, scroll animations, dark mode, and more to create an engaging portfolio experience.',
    tags: ['tech', 'react', 'portfolio', 'generated by AI'],
    readingTime: '8 min',
  },
  {
    title: 'Revamping My Personal Website',
    url: 'revamp',
    date: '2025-06-15',
    description: 'How I redesigned my portfolio using React, TypeScript, and Tailwind CSS with modern interactive features.',
    tags: ['tech', 'portfolio', 'react', 'generated by AI'],
    readingTime: '5 min',
  },
  {
    title: 'Hello World!',
    url: 'hello_world',
    date: '2025-06-12',
    description: 'My first post using MDX. Exploring the power of MDX for blog posts.',
    tags: ['tech', 'tutorial'],
    readingTime: '1 min',
  },
  {
    title: 'Summary',
    url: 'summary',
    date: '2025-06-10',
    description: 'A quick summary of what to expect from this blog.',
    tags: ['personal'],
    readingTime: '1 min',
  },
]

export function getPostsByTag(tag: string): Post[] {
  if (tag === 'all') return POSTS
  return POSTS.filter(post => post.tags.includes(tag))
}

export function getFeaturedPost(): Post | undefined {
  return POSTS.find(post => post.featured)
}

export function getAllTags(): string[] {
  const tags = new Set<string>()
  POSTS.forEach(post => post.tags.forEach(tag => tags.add(tag)))
  return Array.from(tags)
}

export function formatDate(dateString: string): string {
  const date = new Date(dateString)
  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })
}

// Lazy load post components
export function getPostComponent(url: string) {
  switch (url) {
    case 'hello_world':
      return () => import('./hello_word.mdx')
    case 'summary':
      return () => import('./summary.mdx')
    case 'revamp':
      return () => import('./revamp.mdx')
    case 'interactive_features':
      return () => import('./interactive_features.mdx')
    case 'future_coding_ai':
      return () => import('./future_coding_ai.mdx')
    case 'frontend_dev_dead':
      return () => import('./frontend_dev_dead.mdx')
    case 'standout_ai_era':
      return () => import('./standout_ai_era.mdx')
    default:
      return null
  }
}
